name: Build Gradle project
on:
  push:
    branches:
      - main
      - develop
      
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin' # Or other distributions like 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew build
  deploy_to_railway:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Railway
        uses: jzeuzs/action-railway@v1.1.4
        with:
          # The Railway Token
          railway_token: ${{secrets.railway_token}}
